baseurl = "https://zoesmith.io"
languageCode = "en-us"
title = "Zoë Smith"
theme = "hugo-natrium-theme"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "xcode"

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:year-:month-:day/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "Zoë Smith"
    url = "/about/"
    weight = -140

# [[menu.main]]
#     name = "Tags"
#     url = "/tags"
#     weight = -120

# [[menu.main]]
#     name = "Categories"
#     url = "/categories"
#     weight = -130

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[outputFormats]
    [outputFormats.PlainTextFile]
      baseName = "keybase"
      isPlainText = true
      mediaType = "text/plain"
      isHTML = false
