baseurl = "https://zoesmith.io/"
languageCode = "en-us"
title = "Zoë Smith"
theme = "hugo-notepadium"
copyright = "©2018-20 Zoë Smith"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "xcode"

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:year-:month-:day/:slug/"
    page = "/:slug/"

[[params.nav.custom]]
title = "About"
url = "/about"

# [[menu.main]]
#     name = "Zoë Smith"
#     url = "/about/"
#     weight = -140

# [[menu.main]]
#     name = "Tags"
#     url = "/tags"
#     weight = -120

# [[menu.main]]
#     name = "Categories"
#     url = "/categories"
#     weight = -130

[params]
    slogan = ""
    logo = "/images/logo.png"

[params.syntax]
  use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
  theme = "dracula"
  darkTheme = "xcode-dark"  # apply this theme in dark mode
  webFonts = true  # builtin: 'Source Code Pro'

[outputFormats]
    [outputFormats.PlainTextFile]
      baseName = "keybase"
      isPlainText = true
      mediaType = "text/plain"
      isHTML = false

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown
